export {
  type BatchWriteOperation,
  type DeleteItemOptions,
  type DynamoDBCastDefinition,
  type DynamoDBClient,
  DynamoDBModel,
  type DynamoDBModelConstructor,
  type DynamoDBModelHook,
  type DynamoDBModelScope,
  DynamoDBQueryBuilder,
  getModelClient,
  getModelConfig,
  getOrmModelRegistry,
  type PutItemOptions,
  type QueryParameters,
  type QueryResponse,
  type ScanParameters,
  setModelClient,
  setModelConfig,
  setOrmModelRegistry,
  type TransactWriteOperation,
  type UpdateItemOptions,
} from './DynamoDBModel'

// Models Module
// Note: ModelHookType is already exported from ../types.ts, so we use OrmModelHookType here
export {
  type CastDefinition,
  ConditionalCheckFailedError,
  Model,
  type ModelAttribute,
  type ModelConstructor,
  type ModelHook,
  type ModelMetadata,
  ModelNotFoundError,
  type ModelQueryBuilder,
  type ModelRelationship,
  type ModelScope,
  type ModelHookType as OrmModelHookType,
  type QueryResult as OrmQueryResult,
  type SortDirection as OrmSortDirection,
  type PaginationOptions,
  ValidationError,
  type WhereCondition,
  type WhereOperator,
} from './types'
